caila:
  grpcUrl: gate.caila.io
  restUrl: https://caila.io/
  clientToken: <seacreatToken>
  defaultModel:
    model: just-ai/openai-proxy/gpt-4o
    #     model: just-ai/claude/claude-3-haiku
    #     model: just-ai/openai-proxy/gpt-3.5-turbo
    systemPrompt: |
      Ты выступаешь в роли собеседника на интервью.
      Отвечай короткими предложениями, так чтобы собеседник мог вставить слово.
      Задавай вопросы собеседнику, чтобы ему было интересно с тобой разговаривать.
      Если спросят "чем занимаешься", отвечай - провожу интервью

AppUI: false